require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Aether' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'AetherTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.

  # Manual changes: - I manually theses lines below
  # See theses links for more details: 
  # https://stackoverflow.com/questions/66145428/cocoapods-could-not-find-compatible-versions-for-pod-flipper-folly
  # https://stackoverflow.com/questions/54704207/the-ios-simulator-deployment-targets-is-set-to-7-0-but-the-range-of-supported-d

  #use_flipper!()
  #post_install do |installer|
    #react_native_post_install(installer)
  #end

  #use_flipper!({ 'Flipper-Folly' => '~> 2.6' })
  #post_install do |installer|
    #flipper_post_install(installer)
    #react_native_post_install(installer)
      #installer.pods_project.targets.each do |target|
        #target.build_configurations.each do |config|
          #config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        #end
      #end
   #end
end
